// Generated by https://quicktype.io

export interface PokemonListResponse {
  count:    number;
  next:     string;
  previous: null;
  results:  PokemonSchema[];
}

export interface PokemonSchema {
  name: string;
  url:  string;
  id:   number;
  img?:  string;
}
